export type Surface =
  'common' | 'farmer' | 'rsk' | 'mp' | 'operational' | 'voice' | 'device' | 'internal';
export type HttpMethod = 'get' | 'post' | 'patch' | 'delete';

export interface SuccessResponseContract {
  status: 101 | 200 | 201 | 202 | 206;
  description: string;
  mediaType: 'json' | 'binary' | 'websocket';
  responseSchema?: string;
}

export interface QueryParameterContract {
  name: string;
  description: string;
  required: boolean;
  schema:
    | {
        type: 'string';
        format?: 'uuid';
        minLength?: number;
        maxLength?: number;
      }
    | {
        type: 'integer';
        minimum: number;
        maximum: number;
        default?: number;
      };
}

export interface RouteContract {
  method: HttpMethod;
  path: string;
  operationId: string;
  surface: Surface;
  auth: 'none' | 'app-check' | 'identity' | 'farmer' | 'rsk' | 'mp' | 'internal' | 'voice-ticket';
  roleContext?: 'none' | 'optional' | 'required';
  capability?: string;
  purpose?: string;
  requestSchema?: string;
  responseSchema?: string;
  success?: readonly SuccessResponseContract[];
  queryParameters?: readonly QueryParameterContract[];
  rangeRequest?: 'single-byte';
  command?: { idempotency: boolean; expectedRevision: boolean };
  problemCodes: readonly string[];
  classification: 'C0' | 'C1' | 'C2' | 'C3' | 'C4';
  retentionClass: string;
}

const APP_CHECK_PROBLEMS = [
  'AUTHENTICATION_REQUIRED',
  'AUTHORIZATION_DENIED',
  'DEPENDENCY_UNAVAILABLE',
] as const;

const AUTH_PROBLEMS = [...APP_CHECK_PROBLEMS, 'AUTHORIZATION_VERSION_CHANGED'] as const;

export const ROUTES: readonly RouteContract[] = [
  {
    method: 'get',
    path: '/health/live',
    operationId: 'getLiveness',
    surface: 'common',
    auth: 'none',
    responseSchema: 'HealthPayload',
    problemCodes: [],
    classification: 'C0',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/health/ready',
    operationId: 'getReadiness',
    surface: 'common',
    auth: 'none',
    responseSchema: 'HealthPayload',
    problemCodes: ['DEPENDENCY_UNAVAILABLE'],
    classification: 'C0',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/system/reachability',
    operationId: 'getReachability',
    surface: 'common',
    auth: 'none',
    responseSchema: 'HealthPayload',
    problemCodes: [],
    classification: 'C0',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/auth/return-states',
    operationId: 'createReturnState',
    surface: 'common',
    auth: 'app-check',
    requestSchema: 'ReturnStateRequest',
    responseSchema: 'ReturnStateResponse',
    problemCodes: [...APP_CHECK_PROBLEMS, 'RATE_LIMITED'],
    classification: 'C4',
    retentionClass: 'ephemeral-ticket',
  },
  {
    method: 'get',
    path: '/v1/auth/session',
    operationId: 'getAuthSession',
    surface: 'common',
    auth: 'identity',
    responseSchema: 'SessionResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'session',
  },
  {
    method: 'get',
    path: '/v1/auth/roles',
    operationId: 'listRoles',
    surface: 'common',
    auth: 'identity',
    responseSchema: 'SessionResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'session',
  },
  {
    method: 'post',
    path: '/v1/auth/role-contexts',
    operationId: 'selectRoleContext',
    surface: 'common',
    auth: 'identity',
    capability: 'identity.role_context.select',
    requestSchema: 'SelectRoleContextCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'MFA_REQUIRED'],
    classification: 'C2',
    retentionClass: 'command-receipt',
  },
  {
    method: 'delete',
    path: '/v1/auth/role-contexts/{roleContextId}',
    operationId: 'revokeRoleContext',
    surface: 'common',
    auth: 'identity',
    capability: 'identity.role_context.select',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'command-receipt',
  },
  {
    method: 'get',
    path: '/v1/farmer/bootstrap',
    operationId: 'getFarmerBootstrap',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'FarmerBootstrapResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/farmer/consents',
    operationId: 'listFarmerConsents',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'ConsentListResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/farmer/consent-decisions',
    operationId: 'recordConsentDecision',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    requestSchema: 'RecordConsentDecisionCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'consent',
  },
  {
    method: 'post',
    path: '/v1/farmer/setup-drafts',
    operationId: 'saveFarmerSetupDraft',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.setup.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [
      ...AUTH_PROBLEMS,
      'EXPECTED_REVISION_MISMATCH',
      'CONSENT_OR_ACCESS_VERSION_CHANGED',
    ],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'post',
    path: '/v1/farmer/setup:complete',
    operationId: 'completeFarmerSetup',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.setup.complete',
    requestSchema: 'CompleteFarmerSetupCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH', 'SETUP_INCOMPLETE'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'get',
    path: '/v1/farmer/my-farm',
    operationId: 'getMyFarm',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'MyFarmResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/farmer/farms',
    operationId: 'listFarmerFarms',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'MyFarmResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/farmer/farms',
    operationId: 'createFarmerFarm',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.farm.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'get',
    path: '/v1/farmer/farms/{farmId}',
    operationId: 'getFarmerFarm',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'FarmSetup',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'patch',
    path: '/v1/farmer/farms/{farmId}',
    operationId: 'updateFarmerFarm',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.farm.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'post',
    path: '/v1/farmer/farms/{farmId}/plots',
    operationId: 'createFarmerPlot',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.plot.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'get',
    path: '/v1/farmer/plots/{plotId}',
    operationId: 'getFarmerPlot',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'FarmSetup',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/farmer/plots/{plotId}/evidence-summary',
    operationId: 'getFarmerPlotEvidenceSummary',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.evidence.read',
    responseSchema: 'PlotEvidenceSummary',
    problemCodes: [...AUTH_PROBLEMS, 'STALE_DATA'],
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/farmer/plots/{plotId}/recommendation-readiness',
    operationId: 'getFarmerRecommendationReadiness',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.read',
    responseSchema: 'RecommendationReadinessResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/farmer/plots/{plotId}/recommendation-runs',
    operationId: 'createFarmerRecommendationRun',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.run',
    requestSchema: 'RecommendationRequest',
    responseSchema: 'RecommendationRunAcceptedResponse',
    success: [
      {
        status: 202,
        description: 'Accepted',
        mediaType: 'json',
        responseSchema: 'RecommendationRunAcceptedResponse',
      },
    ],
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [
      ...AUTH_PROBLEMS,
      'EXPECTED_REVISION_MISMATCH',
      'EVIDENCE_INSUFFICIENT',
      'SOURCE_RIGHTS_OR_VERSION_INVALID',
    ],
    classification: 'C3',
    retentionClass: 'recommendation-request',
  },
  {
    method: 'get',
    path: '/v1/farmer/recommendation-runs/{operationId}',
    operationId: 'getFarmerRecommendationRun',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.read',
    responseSchema: 'RecommendationRunStatusResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/farmer/recommendations/{recommendationId}',
    operationId: 'getFarmerRecommendation',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.read',
    responseSchema: 'RecommendationResultResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/farmer/recommendations/{recommendationId}/review-requests',
    operationId: 'createFarmerRecommendationReviewRequest',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.review_request',
    requestSchema: 'RecommendationReviewRequest',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'recommendation-review',
  },
  {
    method: 'post',
    path: '/v1/farmer/recommendations/{recommendationId}/acceptances',
    operationId: 'acceptFarmerRecommendation',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.recommendation.accept',
    requestSchema: 'RecommendationAcceptanceRequest',
    responseSchema: 'RecommendationAcceptanceResponse',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [
      ...AUTH_PROBLEMS,
      'EXPECTED_REVISION_MISMATCH',
      'SOURCE_VERSION_EXPIRED',
      'SOURCE_RIGHTS_OR_VERSION_INVALID',
    ],
    classification: 'C3',
    retentionClass: 'recommendation-acceptance',
  },
  {
    method: 'post',
    path: '/v1/farmer/seasons/{seasonId}/start-confirmations',
    operationId: 'confirmFarmerSeasonStart',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.season.start_confirm',
    requestSchema: 'SeasonStartConfirmationRequest',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'season',
  },
  {
    method: 'get',
    path: '/v1/farmer/seasons/{seasonId}/calendar',
    operationId: 'getFarmerSeasonCalendar',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.calendar.read',
    responseSchema: 'SeasonCalendarResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/farmer/plots/{plotId}/soil-records',
    operationId: 'createFarmerSoilRecord',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.soil.write',
    requestSchema: 'CreateSoilRecordRequest',
    responseSchema: 'SoilRecordResponse',
    success: [
      {
        status: 202,
        description: 'Soil evidence record accepted',
        mediaType: 'json',
        responseSchema: 'SoilRecordResponse',
      },
    ],
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'farmer-evidence',
  },
  {
    method: 'patch',
    path: '/v1/farmer/plots/{plotId}',
    operationId: 'updateFarmerPlot',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.plot.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'EXPECTED_REVISION_MISMATCH'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'post',
    path: '/v1/farmer/plots/{plotId}/geometry-versions',
    operationId: 'createFarmerPlotGeometryVersion',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'farmer.plot.write',
    requestSchema: 'SaveFarmerSetupDraftCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'GPS_PERMISSION_DENIED'],
    classification: 'C3',
    retentionClass: 'farmer-setup',
  },
  {
    method: 'patch',
    path: '/v1/farmer/preferences',
    operationId: 'updateFarmerPreferences',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'profile.correct',
    requestSchema: 'UpdateFarmerPreferencesCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'farmer-profile',
  },
  {
    method: 'post',
    path: '/v1/farmer/device-mode-changes',
    operationId: 'changeFarmerDeviceMode',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    capability: 'device_mode.change',
    requestSchema: 'ChangeDeviceModeCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'DEVICE_BINDING_MISMATCH'],
    classification: 'C2',
    retentionClass: 'device-binding',
  },
  {
    method: 'get',
    path: '/v1/rsk/bootstrap',
    operationId: 'getRskBootstrap',
    surface: 'rsk',
    auth: 'rsk',
    responseSchema: 'RskBootstrapResponse',
    problemCodes: [...AUTH_PROBLEMS, 'MFA_REQUIRED'],
    classification: 'C1',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/rsk/access-grants',
    operationId: 'issueRskAccessGrant',
    surface: 'rsk',
    auth: 'rsk',
    capability: 'rsk.access_grant.issue',
    purpose: 'assisted.service',
    requestSchema: 'IssueAccessGrantCommand',
    responseSchema: 'CommandResult',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED'],
    classification: 'C2',
    retentionClass: 'access-grant',
  },
  {
    method: 'post',
    path: '/v1/rsk/protected-disclosures',
    operationId: 'createRskProtectedDisclosure',
    surface: 'rsk',
    auth: 'rsk',
    capability: 'rsk.protected_disclose',
    purpose: 'assisted.service',
    requestSchema: 'ProtectedDisclosureRequest',
    responseSchema: 'ProtectedDisclosureResponse',
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED'],
    classification: 'C3',
    retentionClass: 'audit',
  },
  {
    method: 'get',
    path: '/v1/mp/query-context',
    operationId: 'getMpQueryContext',
    surface: 'mp',
    auth: 'mp',
    responseSchema: 'MpQueryContextResponse',
    problemCodes: [...AUTH_PROBLEMS, 'MFA_REQUIRED', 'DEPENDENCY_UNAVAILABLE'],
    classification: 'C1',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/v1/sync/streams',
    operationId: 'openFarmerSyncStream',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    requestSchema: 'SyncStreamOpenRequest',
    responseSchema: 'SyncStreamOpenResponse',
    problemCodes: [...AUTH_PROBLEMS, 'DEVICE_BINDING_MISMATCH', 'SYNC_SCHEMA_UNSUPPORTED'],
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'post',
    path: '/v1/sync/bootstrap',
    operationId: 'bootstrapFarmerSync',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    requestSchema: 'SyncBootstrapRequest',
    responseSchema: 'SyncBootstrapResponse',
    problemCodes: [...AUTH_PROBLEMS, 'SYNC_SCHEMA_UNSUPPORTED', 'SYNC_CURSOR_INVALID'],
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'post',
    path: '/v1/sync/batches',
    operationId: 'syncFarmerBatch',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    requestSchema: 'SyncBatch',
    responseSchema: 'SyncBatchResponseV2',
    problemCodes: [
      ...AUTH_PROBLEMS,
      'SYNC_BATCH_ID_REUSED',
      'SYNC_CURSOR_INVALID',
      'SYNC_BOOTSTRAP_REQUIRED',
      'SYNC_SCHEMA_UNSUPPORTED',
    ],
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'post',
    path: '/ingest/v1/challenges',
    operationId: 'createDeviceIngestChallenge',
    surface: 'device',
    auth: 'none',
    roleContext: 'none',
    requestSchema: 'DeviceChallengeRequest',
    responseSchema: 'DeviceChallengeResponse',
    problemCodes: ['RATE_LIMITED', 'DEPENDENCY_UNAVAILABLE'],
    classification: 'C1',
    retentionClass: 'device-ingest',
  },
  {
    method: 'post',
    path: '/ingest/v1/batches',
    operationId: 'createDeviceIngestBatch',
    surface: 'device',
    auth: 'none',
    roleContext: 'none',
    requestSchema: 'DeviceBatchRequest',
    responseSchema: 'DeviceReceiptResponse',
    success: [
      {
        status: 202,
        description: 'Telemetry batch durably accepted',
        mediaType: 'json',
        responseSchema: 'DeviceReceiptResponse',
      },
    ],
    problemCodes: [
      'RATE_LIMITED',
      'PAYLOAD_TOO_LARGE',
      'SIGNATURE_INVALID',
      'REPLAY_DETECTED',
      'CHALLENGE_EXPIRED',
      'DEPENDENCY_UNAVAILABLE',
    ],
    classification: 'C2',
    retentionClass: 'device-ingest',
  },
  {
    method: 'get',
    path: '/ingest/v1/receipts/{receiptId}',
    operationId: 'getDeviceIngestReceipt',
    surface: 'device',
    auth: 'none',
    roleContext: 'none',
    responseSchema: 'DeviceReceiptResponse',
    problemCodes: ['AUTHORIZATION_DENIED', 'DEPENDENCY_UNAVAILABLE'],
    classification: 'C1',
    retentionClass: 'device-ingest',
  },
  {
    method: 'post',
    path: '/internal/v1/intelligence/earth-jobs/{jobId}:execute',
    operationId: 'executeEarthObservationJob',
    surface: 'internal',
    auth: 'internal',
    roleContext: 'none',
    requestSchema: 'EarthJobExecuteRequest',
    responseSchema: 'EarthJobExecuteResponse',
    problemCodes: ['AUTHORIZATION_DENIED', 'DEPENDENCY_UNAVAILABLE'],
    classification: 'C3',
    retentionClass: 'earth-observation',
  },
  {
    method: 'get',
    path: '/v1/sync/feed',
    operationId: 'getFarmerSyncFeed',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'SyncFeedPageResponseV2',
    queryParameters: [
      {
        name: 'streamId',
        description: 'Current Farmer sync stream identifier',
        required: true,
        schema: { type: 'string', format: 'uuid' },
      },
      {
        name: 'cursor',
        description: 'Opaque cursor bound to the current stream and authorization',
        required: true,
        schema: { type: 'string', minLength: 1, maxLength: 2048 },
      },
      {
        name: 'limit',
        description: 'Maximum number of feed items to return',
        required: false,
        schema: { type: 'integer', minimum: 1, maximum: 100, default: 100 },
      },
    ],
    problemCodes: [
      ...AUTH_PROBLEMS,
      'SYNC_CURSOR_INVALID',
      'SYNC_CURSOR_EXPIRED',
      'SYNC_BOOTSTRAP_REQUIRED',
    ],
    classification: 'C2',
    retentionClass: 'none',
  },
  {
    method: 'get',
    path: '/v1/sync/commands/{commandId}',
    operationId: 'getFarmerSyncCommand',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'SyncCommandStatusResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'command-receipt',
  },
  {
    method: 'get',
    path: '/v1/sync/conflicts',
    operationId: 'listFarmerSyncConflicts',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'SyncConflictListResponse',
    problemCodes: AUTH_PROBLEMS,
    queryParameters: [
      {
        name: 'cursor',
        description: 'Opaque cursor for the next authorized conflict page',
        required: false,
        schema: { type: 'string', minLength: 1, maxLength: 2048 },
      },
      {
        name: 'limit',
        description: 'Maximum number of conflicts to return',
        required: false,
        schema: { type: 'integer', minimum: 1, maximum: 100, default: 100 },
      },
    ],
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'get',
    path: '/v1/sync/conflicts/{conflictId}',
    operationId: 'getFarmerSyncConflict',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    responseSchema: 'SyncConflict',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'post',
    path: '/v1/sync/conflicts/{conflictId}/resolutions',
    operationId: 'resolveFarmerSyncConflict',
    surface: 'farmer',
    auth: 'farmer',
    purpose: 'farmer.self_service',
    requestSchema: 'SyncConflictResolutionRequest',
    responseSchema: 'SyncCommandStatusResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'INVALID_STATE_TRANSITION'],
    classification: 'C2',
    retentionClass: 'offline-compatibility',
  },
  {
    method: 'post',
    path: '/v1/media/upload-intents',
    operationId: 'createMediaUploadIntent',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'CreateMediaUploadIntentRequest',
    success: [
      {
        status: 201,
        description: 'One-time quarantine upload initiation',
        mediaType: 'json',
        responseSchema: 'CreateMediaUploadIntentResponse',
      },
    ],
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED', 'RATE_LIMITED'],
    classification: 'C4',
    retentionClass: 'media-quarantine',
  },
  {
    method: 'post',
    path: '/v1/media/upload-intents/{intentId}:finalize',
    operationId: 'finalizeMediaUploadIntent',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'FinalizeMediaUploadIntentRequest',
    success: [
      {
        status: 202,
        description: 'Verification accepted',
        mediaType: 'json',
        responseSchema: 'MediaOperationAcceptedResponse',
      },
    ],
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [
      ...AUTH_PROBLEMS,
      'CONSENT_OR_ACCESS_VERSION_CHANGED',
      'MEDIA_INTEGRITY_MISMATCH',
      'UPLOAD_INTENT_EXPIRED',
    ],
    classification: 'C3',
    retentionClass: 'media-quarantine',
  },
  {
    method: 'get',
    path: '/v1/media/assets/{assetId}/status',
    operationId: 'getMediaAssetStatus',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    responseSchema: 'MediaAssetStatusResponse',
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED'],
    classification: 'C2',
    retentionClass: 'none',
  },
  {
    method: 'delete',
    path: '/v1/media/upload-intents/{intentId}',
    operationId: 'cancelMediaUploadIntent',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    responseSchema: 'CancelMediaUploadIntentResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'INVALID_STATE_TRANSITION'],
    classification: 'C2',
    retentionClass: 'media-quarantine',
  },
  {
    method: 'get',
    path: '/v1/media/attachments/{attachmentId}/content',
    operationId: 'streamMediaAttachment',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    rangeRequest: 'single-byte',
    success: [
      { status: 200, description: 'Complete generation-pinned attachment', mediaType: 'binary' },
      { status: 206, description: 'Single authorized byte range', mediaType: 'binary' },
    ],
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED', 'MEDIA_NOT_VERIFIED'],
    classification: 'C3',
    retentionClass: 'none',
  },
  {
    method: 'post',
    path: '/internal/v1/media/assets/{assetId}:scan',
    operationId: 'scanMediaAsset',
    surface: 'internal',
    auth: 'internal',
    requestSchema: 'ScanMediaAssetRequest',
    success: [
      {
        status: 202,
        description: 'Scan claimed by the media scanner',
        mediaType: 'json',
        responseSchema: 'MediaOperationAcceptedResponse',
      },
    ],
    problemCodes: [
      'AUTHENTICATION_REQUIRED',
      'AUTHORIZATION_DENIED',
      'DEPENDENCY_UNAVAILABLE',
      'MEDIA_INTEGRITY_MISMATCH',
    ],
    classification: 'C3',
    retentionClass: 'media-quarantine',
  },
  {
    method: 'post',
    path: '/v1/voice/sessions',
    operationId: 'createVoiceSession',
    surface: 'voice',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'CreateVoiceSessionRequest',
    success: [
      {
        status: 201,
        description: 'Bound one-time voice ticket',
        mediaType: 'json',
        responseSchema: 'CreateVoiceSessionResponse',
      },
    ],
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'RATE_LIMITED'],
    classification: 'C4',
    retentionClass: 'voice-session',
  },
  {
    method: 'get',
    path: '/v1/realtime',
    operationId: 'openVoiceRealtime',
    surface: 'voice',
    auth: 'voice-ticket',
    roleContext: 'none',
    success: [
      { status: 101, description: 'sfka.voice.v1 WebSocket upgrade', mediaType: 'websocket' },
    ],
    problemCodes: [...AUTH_PROBLEMS, 'RATE_LIMITED'],
    classification: 'C4',
    retentionClass: 'ephemeral-ticket',
  },
  {
    method: 'post',
    path: '/v1/voice/sessions/{sessionId}/turns',
    operationId: 'createVoiceTurn',
    surface: 'voice',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'VoiceTurnRequest',
    responseSchema: 'VoiceTurnResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'DEPENDENCY_UNAVAILABLE'],
    classification: 'C4',
    retentionClass: 'voice-session',
  },
  {
    method: 'get',
    path: '/v1/voice/proposals/{proposalId}',
    operationId: 'getVoiceProposal',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    responseSchema: 'VoiceProposalResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C3',
    retentionClass: 'voice-proposal',
  },
  {
    method: 'post',
    path: '/v1/voice/proposals/{proposalId}:confirm',
    operationId: 'confirmVoiceProposal',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'ConfirmVoiceProposalRequest',
    responseSchema: 'VoiceCommandStatusResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'VOICE_PROPOSAL_EXPIRED', 'VOICE_PROPOSAL_HASH_MISMATCH'],
    classification: 'C3',
    retentionClass: 'command-receipt',
  },
  {
    method: 'post',
    path: '/v1/voice/proposals/{proposalId}:correct',
    operationId: 'correctVoiceProposal',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'CorrectVoiceProposalRequest',
    responseSchema: 'VoiceProposalResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'VOICE_PROPOSAL_EXPIRED'],
    classification: 'C3',
    retentionClass: 'voice-proposal',
  },
  {
    method: 'post',
    path: '/v1/voice/proposals/{proposalId}:cancel',
    operationId: 'cancelVoiceProposal',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'CancelVoiceProposalRequest',
    responseSchema: 'VoiceProposalResponse',
    command: { idempotency: true, expectedRevision: false },
    problemCodes: [...AUTH_PROBLEMS, 'VOICE_PROPOSAL_EXPIRED'],
    classification: 'C2',
    retentionClass: 'voice-proposal',
  },
  {
    method: 'get',
    path: '/v1/commands/{commandId}',
    operationId: 'getVoiceCommandStatus',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    responseSchema: 'VoiceCommandStatusResponse',
    problemCodes: AUTH_PROBLEMS,
    classification: 'C2',
    retentionClass: 'command-receipt',
  },
  {
    method: 'post',
    path: '/v1/voice/offline-audio',
    operationId: 'attachVoiceOfflineAudio',
    surface: 'operational',
    auth: 'identity',
    roleContext: 'required',
    requestSchema: 'AttachOfflineAudioRequest',
    responseSchema: 'AttachOfflineAudioResponse',
    command: { idempotency: true, expectedRevision: true },
    problemCodes: [...AUTH_PROBLEMS, 'CONSENT_OR_ACCESS_VERSION_CHANGED', 'MEDIA_NOT_VERIFIED'],
    classification: 'C3',
    retentionClass: 'voice-offline-audio',
  },
] as const;
