import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const defaultPackageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const defaultIo = { mkdir, readFile, writeFile };

export function createOutputs(source, generatedRoot) {
  assertCanonicalSource(source);

  const { contractVersion, serviceHealth } = source;
  const healthSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://smart-fasal.example/contracts/health.schema.json',
    title: 'HealthPayload',
    type: 'object',
    additionalProperties: false,
    required: ['service', 'status', 'timestamp'],
    properties: {
      service: { type: 'string', minLength: 1 },
      status: { type: 'string', enum: serviceHealth.statuses },
      timestamp: { type: 'string', format: 'date-time' },
    },
  };

  const openApi = {
    openapi: '3.1.0',
    info: {
      title: 'Smart Fasal platform health contract',
      version: contractVersion,
    },
    paths: {
      [serviceHealth.livePath]: {
        get: {
          operationId: 'getLiveness',
          responses: {
            200: healthResponse('Process is alive'),
          },
        },
      },
      [serviceHealth.readyPath]: {
        get: {
          operationId: 'getReadiness',
          responses: {
            200: healthResponse('Service dependencies are ready'),
            503: healthResponse('A required dependency is unavailable'),
          },
        },
      },
    },
    components: { schemas: { HealthPayload: healthSchema } },
  };

  const eventCatalog = {
    contractVersion,
    events: source.events,
  };

  const typescriptModule = `// Generated by scripts/generate.mjs. Do not edit by hand.
export const contractVersion = ${JSON.stringify(contractVersion)} as const;
export const serviceHealth = ${JSON.stringify(serviceHealth, null, 2)} as const;

export type HealthStatus = (typeof serviceHealth.statuses)[number];

export interface HealthPayload {
  service: string;
  status: HealthStatus;
  timestamp: string;
}

export function isHealthPayload(value: unknown): value is HealthPayload {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const candidate = value as Record<string, unknown>;
  const keys = Object.keys(candidate);
  return (
    keys.length === 3 &&
    keys.every((key) => key === 'service' || key === 'status' || key === 'timestamp') &&
    typeof candidate['service'] === 'string' &&
    candidate['service'].length > 0 &&
    typeof candidate['status'] === 'string' &&
    (serviceHealth.statuses as readonly string[]).includes(candidate['status']) &&
    typeof candidate['timestamp'] === 'string' &&
    !Number.isNaN(Date.parse(candidate['timestamp']))
  );
}
`;

  const javascriptModule = `// Generated by scripts/generate.mjs. Do not edit by hand.
export const contractVersion = ${JSON.stringify(contractVersion)};
export const serviceHealth = ${JSON.stringify(serviceHealth, null, 2)};

export function isHealthPayload(value) {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return false;
  const keys = Object.keys(value);
  return (
    keys.length === 3 &&
    keys.every((key) => key === 'service' || key === 'status' || key === 'timestamp') &&
    typeof value.service === 'string' &&
    value.service.length > 0 &&
    serviceHealth.statuses.includes(value.status) &&
    typeof value.timestamp === 'string' &&
    !Number.isNaN(Date.parse(value.timestamp))
  );
}
`;

  const pythonStatusLiteral = serviceHealth.statuses
    .map((status) => JSON.stringify(status))
    .join(', ');
  const pythonModule = `# Generated by scripts/generate.mjs. Do not edit by hand.
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

CONTRACT_VERSION: Literal[${JSON.stringify(contractVersion)}] = ${JSON.stringify(contractVersion)}
HealthStatus = Literal[${pythonStatusLiteral}]


class HealthPayload(BaseModel):
    model_config = ConfigDict(extra="forbid")

    service: str = Field(min_length=1)
    status: HealthStatus
    timestamp: datetime
`;

  const pythonPackage = `# Generated by scripts/generate.mjs. Do not edit by hand.
from .health import CONTRACT_VERSION, HealthPayload, HealthStatus

__all__ = ["CONTRACT_VERSION", "HealthPayload", "HealthStatus"]
`;

  return new Map([
    [
      resolve(generatedRoot, 'openapi/platform.openapi.json'),
      `${JSON.stringify(openApi, null, 2)}\n`,
    ],
    [
      resolve(generatedRoot, 'json-schema/health.schema.json'),
      `${JSON.stringify(healthSchema, null, 2)}\n`,
    ],
    [
      resolve(generatedRoot, 'events/event-catalog.json'),
      `${JSON.stringify(eventCatalog, null, 2)}\n`,
    ],
    [resolve(generatedRoot, 'typescript/index.ts'), typescriptModule],
    [resolve(generatedRoot, 'javascript/index.js'), javascriptModule],
    [resolve(generatedRoot, 'pydantic/smart_fasal_contracts/__init__.py'), pythonPackage],
    [resolve(generatedRoot, 'pydantic/smart_fasal_contracts/health.py'), pythonModule],
    [resolve(generatedRoot, 'pydantic/smart_fasal_contracts/py.typed'), ''],
  ]);
}

export async function generateContracts({
  checkOnly = false,
  io = defaultIo,
  packageRoot = defaultPackageRoot,
} = {}) {
  const sourcePath = resolve(packageRoot, 'source/platform.json');
  const generatedRoot = resolve(packageRoot, 'generated');
  const source = JSON.parse(await io.readFile(sourcePath, 'utf8'));
  const outputs = createOutputs(source, generatedRoot);
  let changed = false;

  for (const [path, expected] of outputs) {
    let current;
    try {
      current = await io.readFile(path, 'utf8');
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }

    if (current === expected) continue;
    changed = true;

    if (!checkOnly) {
      await io.mkdir(dirname(path), { recursive: true });
      await io.writeFile(path, expected, 'utf8');
    }
  }

  return changed;
}

export async function runCli({ argv = process.argv, logger = console, ...options } = {}) {
  const checkOnly = argv.includes('--check');
  const changed = await generateContracts({ ...options, checkOnly });

  if (checkOnly && changed) {
    logger.error('Generated contracts are out of date. Run pnpm contracts:generate.');
    return 1;
  }

  return 0;
}

function healthResponse(description) {
  return {
    description,
    content: {
      'application/json': {
        schema: { $ref: '#/components/schemas/HealthPayload' },
      },
    },
  };
}

export function assertCanonicalSource(value) {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError('Contract source must be an object');
  }
  if (typeof value.contractVersion !== 'string' || value.contractVersion.length === 0) {
    throw new TypeError('contractVersion must be a non-empty string');
  }
  if (!Array.isArray(value.events)) throw new TypeError('events must be an array');
  if (
    typeof value.serviceHealth !== 'object' ||
    value.serviceHealth === null ||
    Array.isArray(value.serviceHealth)
  ) {
    throw new TypeError('serviceHealth must be an object');
  }
  for (const key of ['livePath', 'readyPath']) {
    if (typeof value.serviceHealth[key] !== 'string' || !value.serviceHealth[key].startsWith('/')) {
      throw new TypeError(`serviceHealth.${key} must be an absolute path`);
    }
  }
  if (
    !Array.isArray(value.serviceHealth.statuses) ||
    value.serviceHealth.statuses.length === 0 ||
    value.serviceHealth.statuses.some((status) => typeof status !== 'string') ||
    new Set(value.serviceHealth.statuses).size !== value.serviceHealth.statuses.length
  ) {
    throw new TypeError('serviceHealth.statuses must contain unique strings');
  }
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : undefined;
if (invokedPath === fileURLToPath(import.meta.url)) {
  process.exitCode = await runCli();
}
